### ISSUE TITLE
Add ExpectHelper to docs

### ISSUE THREAD

**Issue by kobenguyent** [codeceptjs/website#397]
Hi @Arhell, please help add this new Expect helper to docs and sync with latest changes of CodeceptJS release. 

https://codecept.io/helpers/Expect/

This doc is right now only accessible directly from that link. Would be nice to add it to the Nav or somewhere similar.

**Comment by Arhell** [comment]
@kobenguyent 
Alas, it doesn’t work out, most likely there are no rights, I thought the problem was in the node, but not
@DavertMik cc

**Comment by Arhell** [comment]
@kobenguyent
https://github.com/codeceptjs/codeceptjs.github.io/commit/28c18087ad4e547885139d9bcd68503a5093edc9
